### PR TITLE
fix(ui): Fixed deletion of wrongly linked releases

### PR DESCRIPTION
**Pull request by ChristophNiehoff**
* For linking releases and projects to projects changed the id for the rows in the Linked Releases and Projects-Table in the project edit view.
* At the same time also fixed an error in the projects and releases search dialogs

Closes sw360/sw360portal#541

### CODE REVIEW

**Comment by ChristophNiehoff** [comment]
The bug described in #541 originated from the fact that the "Linked Projects"- and "Linked Releases"-tables in the projects edit view contained rows with the same id. This led to conflicts when removing these rows. Changed the row ids to project's and release's ids for uniqueness.

**Comment by alexbrdn** [comment]
@adrian-evo, could you test the fix, please?

**Comment by adrian-evo** [comment]
Cannot check due to #541

**Comment by mcjaeger** [comment]
@adrian-evo did you mean https://github.com/sw360/sw360portal/pull/561

**Comment by adrian-evo** [comment]
Yes, #561 as #553 reproduces also in this branch.

**Comment by alexbrdn** [comment]
@ChristophNiehoff , please rebase. I've merged #561

**Comment by ChristophNiehoff** [comment]
rebased on the current master

**Comment by alexbrdn** [comment]
I performed a cursory test, but would still like a second opinion on the correctness of the fix before merging. @adrian-evo, I'd appreciate your take on it.

**Comment by adrian-evo** [comment]
Tested various scenarios, works as expected.

**Pull request merged**
