### PR TITLE
Show Hierarchy Level at LicenseInfo Generation Page

### LINKED ISSUE #305: Show level of component hierarchy when creating a license information file (ReadmeOSS)
When you have a project which consists of components and also other projects, which themselves contain other projects you get a very big list of components in the license information file generation window and for comfortability and avoiding mistakes it would be good to see the hierarchical level number of each component in the beginning of the selection entry.

### PR DESCRIPTION
**Pull request by alex-evo**
Added column for showing tree level of releases and projects at licenseInfo generation

Closes #305

### CODE REVIEW

**Comment by mcjaeger** [comment]
There seems to be an issue with the colspan in the first table header row. (see screenshot) 
Also, my proposal is to change "LVL" to "Level" or at least "Lvl" because "LVL" appears really dominating here. (this is an optical impression issue for me here)

screen shot 2016-12-22 at 14 17 38

**Comment by mcjaeger** [comment]
For the hierarchy, it seems like there is for every node, starting with `0`:

screen shot 2016-12-22 at 14 29 39
(note the indentation)

**Comment by alex-evo** [comment]
That colspan always gets me. Fixed it and changed column title to Lvl.

Are you sure you've deployed cleanly? Because I can't reproduce the problem with level numbering. Looks like this for me:
image

**Comment by alex-evo** [comment]
UPDATE: added showing tree level in attachment rows, where it was missing before

**Comment by mcjaeger** [comment]
works and looks good!
tested-by: michael.c.jaeger@siemens.com

**Comment by mcjaeger** [comment]
@maximilianhuber, @bs-jokri  I think the code changes are very small, would you be OK if take over the review role for this pull request?

**Pull request merged**
