### PR TITLE
chore(ui): add pattern format to all input datepicker

### PR DESCRIPTION
**Pull request by maierthomas**
- add YYYY-MM-DD pattern to all input datepicker
`pattern="\d{4}-\d{1,2}-\d{1,2}"`

closes sw360/sw360portal#174

### CODE REVIEW

**Comment by maierthomas** [comment]
for `Created on` on releases or projects we have the date format dd/mm/yyyy

**Comment by adrian-evo** [comment]
For projects works as expected, I cannot create/update the project if the date format is invalid.

For releases, Release Date, Evaluation Start and End fields, the date format is not validated.

**Comment by maierthomas** [comment]
@adrian-evo could you please retest the branch? the releases should be validate now!

**Comment by adrian-evo** [comment]
Works also for releases now.

**Pull request merged**
