### PR TITLE
fix(projects): Links to linked releases from project details page didn't work

### PR DESCRIPTION
**Pull request by alexbrdn**
Links to linked releases from project details page and from moderation pages didn't work. 
Links to main licenses were missing entirely.

### CODE REVIEW

**Comment by mcjaeger** [comment]
Just ran the branch on an existing instance with updating, and it does not seem to work:

1. go to the project listing of linked releases and projects
2. click on one entry
3. error message appears: component portlet not available

Deleted cache and all files: no change.

exception from log:
```
15:26:41,331 ERROR [http-bio-8080-exec-352][PortletRequestDispatcherImpl:115] org.apache.jasper.JasperException: An exception occurred processing JSP page /html/components/includes/releases/summaryRelease.jspf at line 72__69:         <tr>_70:             <td>Main Licenses:</td>_71:             <td>_72:                 <sw360:DisplayLicenseCollection licenseIds="${release.mainLicenseIds}" scopeGroupId="${pageContext.getAttribute('scopeGroupId')}"/>_73:             </td>_74:         </tr>_75:         <tr>___Stacktrace: [Sanitized]
org.apache.jasper.JasperException: An exception occurred processing JSP page /html/components/includes/releases/summaryRelease.jspf at line 72__69:         <tr>_70:             <td>Main Licenses:</td>_71:             <td>_72:                 <sw360:DisplayLicenseCollection licenseIds="${release.mainLicenseIds}" scopeGroupId="${pageContext.getAttribute('scopeGroupId')}"/>_73:             </td>_74:         </tr>_75:         <tr>___Stacktrace: [Sanitized]
	at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:575)

```

**Comment by mcjaeger** [comment]
restested also with 
1. delete all artifacts from maven repo
2. undeploy sw360-portlet before deploying
-> error is still there.

**Comment by alexbrdn** [comment]
Hmmm, I'll have to have a look at it.

**Comment by mcjaeger** [comment]
somehow it is linked to the test data: 
1. new vagrant install
2. import the test data
3. calling component main list fails with exception:
```
Jul 21, 2017 6:17:25 AM org.apache.catalina.core.ApplicationDispatcher invoke
SEVERE: Servlet.service() for servlet jsp threw exception
java.lang.NullPointerException
	at org.eclipse.sw360.portal.tags.links.DisplayLicenseCollection.doStartTag(DisplayLicenseCollection.java:42)
	at org.apache.jsp.html.components.view_jsp._jspx_meth_sw360_005fDisplayLicenseCollection_005f0(view_jsp.java:1448)
	at org.apache.jsp.html.components.view_jsp._jspx_meth_core_005frt_005fset_005f4(view_jsp.java:1417)
	at org.apache.jsp.html.components.view_jsp._jspService(view_jsp.java:882)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
```

**Comment by mcjaeger** [comment]
nope, when running the stage listing components crashes with "components portlet available" and the following exception:

```
21-Jul-2017 12:22:03.932 SEVERE [http-nio-8080-exec-746] org.apache.catalina.core.ApplicationDispatcher.invoke Servlet.service() for servlet jsp threw exception
 java.lang.NullPointerException
        at org.eclipse.sw360.portal.tags.links.DisplayLicenseCollection.doStartTag(DisplayLicenseCollection.java:42)
        at org.apache.jsp.html.components.view_jsp._jspx_meth_sw360_005fDisplayLicenseCollection_005f0(view_jsp.java:1485)
        at org.apache.jsp.html.components.view_jsp._jspx_meth_core_005frt_005fset_005f4(view_jsp.java:1454)
        at org.apache.jsp.html.components.view_jsp._jspService(view_jsp.java:919)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
```
-> we could merge it because it runs some instances, but it would fail on productive

**Comment by alexbrdn** [comment]
@mcjaeger, I've added a check for `null` and rebased the branch. Please retest.

**Pull request merged**
