### PR TITLE
feat(ui): improve handling of country fields

### PR DESCRIPTION
**Pull request by maierthomas**
- added two new tags (display name, display options)
- ISO-3166-1 / Alpha 2 Codes
- configurable preferred country code list in sw360.properties
(preferred.country.codes: DE,AT,CH,US)

closes sw360/sw360portal#750

### CODE REVIEW

**Comment by adrian-evo** [comment]
There is a build failure, the error is:

[ERROR] Failed to execute goal on project sw360-portlet: Could not resolve dependencies for project org.eclipse.sw360:sw360-portlet:war:3.2.0-SNAPSHOT: Failed to collect dependencies for [org.eclipse.sw360:datahandler:jar:3.2.0-SNAPSHOT (compile)...

**Comment by adrian-evo** [comment]
OK, it seems there is a new module and download is not working behind the proxy. I will try later without proxy.

**Comment by maierthomas** [comment]
yes I added a new dependency, please see the pom.xml file.
this dependency resolves the country code list.
Otherwise we need to switch to java Locale or hardcoded country code and names.

```
<dependency>
            <groupId>com.neovisionaries</groupId>
            <artifactId>nv-i18n</artifactId>
            <version>1.22</version>
</dependency>
```

**Comment by adrian-evo** [comment]
Works as expected.

**Comment by maierthomas** [comment]
please use java locale for the country code list

**Comment by maierthomas** [comment]
changed to java Locale.
removed dependency 'com.neovisionaries'

**Comment by adrian-evo** [comment]
Tested ok.

**Comment by maierthomas** [comment]
Added Wiki
----------------
https://github.com/sw360/sw360portal/wiki/Configuration-Country-Codes

countrycodelist

**Pull request merged**
