### PR TITLE
Number of cves displayed on component and release view

### PR DESCRIPTION
**Pull request by bs-jokri**
This PR adds a the number of found cves to views of release and component

### CODE REVIEW

**Comment by maximilianhuber** [comment]
related screenshot:
ea3905fc-c207-11e6-95e1-43209e946a62

**Comment by mcjaeger** [comment]
I vote for unique vulnerabilities on component level (in this case 6)

**Comment by bs-jokri** [comment]
Unique vulnerabilites are the best option. Maybe we should add a tooltip that explains that the vulnerability number on component level represents the unique number of vulnerabilities over all releases of this component.

**Comment by mcjaeger** [comment]
merged via https://github.com/sw360/sw360portal/commit/7b050081dc0e544270b0853f62b82c406dc5733d

**Pull request closed without merging**
