### PR TITLE
support couchdb scurity settings for restricting view access

### PR DESCRIPTION
**Pull request by bs-jokri**
Allows credentials based connections via ektorp layer.
most of the code is taken from the Ektorp project
  - i.e. see https://github.com/helun/Ektorp/commit/1b534a99c689661e81aa497ba4f05e143eca8e04

### CODE REVIEW

**Comment by mcjaeger** [comment]
@maximilianhuber @bs-jokri 

could you pls explain how this is going to work? I would need some idea how to test it.

What I did:

1. deploy build form branch from bsinno:fix/intIssue#289
2. shutdown sw360
3. create /etc/sw360/couchdb.properties
4. enter some user password
5. start sw360

-> no auto set password kicked in / nothing changed

**Comment by maximilianhuber** [comment]
If you have a look at the security settings of databases in couchdb, i.e. by opening Futon, you will see the following:
security

This implies, that **if the system has an registered admin user** (and the admin party is over), only admins are able to see the contents of our databases.

**Comment by mcjaeger** [comment]
ah, so I need to have an empty couchdb and setup admin role first? and then it is for auto creation of the db?

**Comment by mcjaeger** [comment]
tested-by:michael.c.jaeger@siemens.com
review-by:michael.c.jaeger@siemens.com

**Comment by mcjaeger** [comment]
tested-by:michael.c.jaeger@siemens.com
review-by:michael.c.jaeger@siemens.com

**Pull request merged**
