### PR TITLE
fix(spdx): `getAllLicenseTexts` was not called due to merge failure

### PR DESCRIPTION
**Pull request by maximilianhuber**
The generated reports does not include all license information due to a merge failure.

### CODE REVIEW

**Comment by mcjaeger** [comment]
OK, but could you pls. provide some information how to test it? something like take example file YXZ -> now chowing licenses from section ABC ...

**Comment by maximilianhuber** [comment]
The example is `SPDXRdfExample-v2.0.rdf` in which the old version only extracts 5 licenses and the patched code finds 7 (see https://github.com/sw360/sw360portal/pull/368/files#diff-bc64ea2c4db63933f9a7e07f081a9797R68).

I will try to find out which license is affected and why.

**Comment by maximilianhuber** [comment]
@mcjaeger the buggy implementation misses the LGPL in https://raw.githubusercontent.com/spdx/tools/master/TestFiles/SPDXRdfExample-v2.0.rdf.

##

another question: the testfile contains
```
[...]
PackageLicenseInfoFromFiles: GPL-2.0
[...]
LicenseInfoInFile: GPL-2.0
[...]
```
but we currently only look at the concluded licenses. Should we also pay attention to the `licenseInfoInFile` information?

**Comment by maximilianhuber** [comment]
This closes https://github.com/sw360/sw360portal/issues/236

**Comment by mcjaeger** [comment]
@maximilianhuber I think focus concluded licenses and not putting found licenses is needed because licenses found by scanners could be wrong / false positives with significant probability.

**Comment by mcjaeger** [comment]
@maximilianhuber I am sorry I cannot see that Apache is in now in the generated text document (thanks for the link to the issue though)

**Pull request merged**
