### PR TITLE
chores(rake): fix minor bug in docker call

### PR DESCRIPTION
**Pull request by maximilianhuber**
the previously set volume for the `.m2`-repository-cache was not valid.

(this fixes a feature which is apparently only used by me)

### CODE REVIEW

**Comment by alex-evo** [comment]
I'm curious: what is this feature?

**Comment by maximilianhuber** [comment]
@alex-evo instead of installing Java and Thrift-Compiler locally on your machine you can call
```
rake compile
```
to run a `mavn install` in a dockerized environment.

This also works for deployment and packaging.

**Comment by alex-evo** [comment]
Thanks! I really ought to embrace The Docker Way

**Comment by alex-evo** [comment]
FWIW, `rake compile` fails on my machine with the following error:
```
+ apt-get install -y --no-install-recommends openjdk-8-jdk maven
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 maven : Depends: libaether-java but it is not going to be installed
         Depends: libsisu-ioc-java but it is not going to be installed
 openjdk-8-jdk : Depends: openjdk-8-jre (= 8u121-b13-1~bpo8+1) but it is not going to be installed
                 Depends: openjdk-8-jdk-headless (= 8u121-b13-1~bpo8+1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Removing intermediate container f39f2f92f9e7
The command '/bin/sh -c set -x  && echo "deb http://ftp.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/backports.list  && $_update && $_install openjdk-8-jdk maven && $_cleanup  && update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  && echo "JAVA_HOME=\"/usr/lib/jvm/java-8-openjdk-amd64/jre\"" >> /etc/environment' returned a non-zero code: 100
rake aborted!
Command failed with status (100): [cat sw360dev.Dockerfile | docker build -t ...]

```

**Comment by maximilianhuber** [comment]
@alex-evo  the problem should now be fixed. The container is now based on an image already contianing maven and jdk-8.

**Pull request merged**
