### PR TITLE
chore(mvn): add jgitver support

### PR DESCRIPTION
**Pull request by alexbrdn**

### CODE REVIEW

**Comment by maximilianhuber** [comment]
Sadly this does not work. Since the dependencies within SW360 stay at 0.0.0

**Comment by maximilianhuber** [comment]
The problem together with a minimal example is described at https://github.com/jgitver/jgitver-maven-plugin/issues/54

**Comment by maximilianhuber** [comment]
This also breaks the possibility to compile only subprojects

**Comment by maximilianhuber** [comment]
https://github.com/jgitver/jgitver-maven-plugin/issues/40 might be related

**Comment by maximilianhuber** [comment]
A good alternative would be to use a bare `git describe`, which generates an output of the following form:
```
$ git describe
sw360-1.6.0-15-g53211535
```
where
- `sw360-1.6.0` is the most recent tag
- `15` is the number of commits since found tag
- `g53211535` is the commit hash of the current commit.

This might allow us to create versioning for CI.

This does not yet show the branch on which one currently is.

**Comment by maximilianhuber** [comment]
Idea: show the result of `git describe` in the footer but do not set it hard as version. For CI one could use an plugin to generate custom versions

**Comment by alexbrdn** [comment]
@maximilianhuber, this topic appears to be stalled. I suggest that we close the PR for now and reconsider it at a later date. What's your take on it?

**Comment by maximilianhuber** [comment]
Yes you are right. But I think a lightweight release process is already a partial solution.

**Comment by mcjaeger** [comment]
" But I think a lightweight release process is already a partial solution. " -> what would that be (please help)

**Comment by maximilianhuber** [comment]
Our current setup with the semantic versioning already allows for a fast release of a new Minor/Patch version. Thus, if one wants to deploy the latest state and at the same time a tagged state, it is not much overhead to tag the current master.

**Pull request closed without merging**
