### PR TITLE
Component merge wizzard check that components' ids are not same.

### PR DESCRIPTION
**Pull request by kallesoranko**
closes sw360/sw360portal#697

### CODE REVIEW

**Comment by maierthomas** [comment]
thank you for contributing!!

please note the following wiki pages:
https://github.com/sw360/sw360portal/wiki/Dev-DoD-and-Style
https://github.com/sw360/sw360portal/wiki/Dev-Semantic-Commits

**Comment by kallesoranko** [comment]
Thanks @maierthomas , I was actually looking for something about commit messages, great

**Comment by kallesoranko** [comment]
closes sw360/sw360portal#697

**Comment by mcjaeger** [comment]
(adding label do not merge because of the committer agreement)

**Comment by kallesoranko** [comment]
contributor agreement done

**Comment by kallesoranko** [comment]
waiting for employer agreement

**Pull request merged**
