### PR TITLE
chore(rest): Update for REST API documentation

### PR DESCRIPTION
**Pull request by maierthomas**
- changed subtitle and hierarchy level
- added status code
- added chapter 'Token'
- added some fields for components and projects

### CODE REVIEW

**Comment by maxhbr** [comment]
Maybe also mention that the java-web-token can be decoded on https://jwt.io/

As a result one gets:
#### Header:
```
{
  "alg": "RS256",
  "typ": "JWT"
}
```
#### Payload
```
{
  "aud": [
    "sw360-REST-API"
  ],
  "user_name": "user1@sw360.org",
  "scope": [
    "all"
  ],
  "exp": 1515779086,
  "authorities": [
    "READ",
    "WRITE"
  ],
  "jti": "699c2af1-562b-4468-990f-2612b37bf7c9",
  "client_id": "trusted-sw360-client"
}
```

## Unrelated question:
Why does the `user1` get the authority `WRITE`? I think that users no longer have write access and thus should no longer contain that information in the jwt?

**Comment by maierthomas** [comment]
Yes we should think about the decode option for the JWT.
Maybe we can implement this feature to reduce the annoying and long tokens.

I just want to remember that this PR is only about the enhancement of the API documentation.
Lets clarify the second part regarding the authorities in separate call.

**Comment by maxhbr** [comment]
I just want to suggest to mention https://jwt.io/ in the documention about the token. I do not want to suggest anything to implement or so

**Comment by maierthomas** [comment]
Oh ok. Good information.
I was confused, I thought it needs to be implemented.

On my configuration I received for user1 the following:

```
{
  "aud": [
    "sw360-REST-API"
  ],
  "user_name": "user1@sw360.org",
  "scope": [
    "all"
  ],
  "exp": 1516023229,
  "authorities": [
    "READ"
  ],
  "jti": "073c9065-b11c-46a9-a5e4-371144c57341",
  "client_id": "trusted-sw360-client"
}
```

**Comment by maxhbr** [comment]
My information is from your token in the documentation

**Comment by maierthomas** [comment]
Ahhh okay...
the JWT was generated on our siemens dev system of sw360.
This system is configured as the following:
rest.write.access.usergroup=USER
Every user which belongs to usergroup USER is admin... :)
I will replace this JWT and add information about the encode decode option

**Comment by maierthomas** [comment]
- added jwt.io decode information
- changed access token value
- added documentation for vulnerabilities

**Comment by maierthomas** [comment]
#712 needs to be merged first!

**Pull request merged**
