### PR TITLE
autocomplete for component categories

### LINKED ISSUE #82: Adding predefined categories to type (of component): DOAP
In some earlier  version there was a pull down menue, like as with programming languages for the component types.

So the user did not have free form, but a list to select from.

That should be back again. And is should based on an already established standard:

https://projects-old.apache.org/categories.html

(adding "other" mght be useful as well)

If could be implemented the same way it is done with platforms or programming languages.

### PR DESCRIPTION
**Pull request by alex-evo**
Added autocomplete suggestions for component categories.
The list of suggested categories can be edited in sw360.properties
Closes #82

### CODE REVIEW

**Comment by mcjaeger** [comment]
the pull request appears rather small in terms of LOC what are the conflicts actually?

**Comment by alex-evo** [comment]
the conflicts were in PortalConstants and sw360.properties. rebased/resolved.

**Comment by mcjaeger** [comment]
review-by: michael.c.jaeger@siemens.com
tested-by: michael.c.jaeger@siemens.com
actually also tested changing the list. Did direct edit of the two files because of having library and Library entries, but actually commit history looks bad - squash it?
other wise it could be merged directly.

**Comment by alex-evo** [comment]
Github can squash when merging, can it not?

**Pull request merged**
