### PR TITLE
feat(lics): also import and export external IDs

### PR DESCRIPTION
**Pull request by maxhbr**
also add (optional) external IDs for Licenses and TODOs (only used while importing and exporting)

### CODE REVIEW

**Comment by mcjaeger** [comment]
how to test it?

* create some licenses (maybe A B C) and then some todos (maybe 1 2 3)
* then export the licesenses (in the admin section)
* Then open the *.lics archive (using unzipper tool)
* edit the text file with the todos
* change some external Ids there for todo (maybe go to TODO 1 and then add some external id)
* then compress again the folder with the files inside
* rename extension to *.lics again
* then clean up the database (remove all licenses and todos)
* try to upload / import to an empty database.

-> then look into the couchdb if the license todo has a externalid

**Comment by adrian-evo** [comment]
Tested and seems to work partially for License IDs, however importing TODOs is not working due to #625 

Even if a single license and a single TODO is exported and imported back, the TODO is not imported.

**Comment by maxhbr** [comment]
@adrian-evo You need to add the todos via import and not via the ui. Then it will work.

One might be able to fix that by adding the sw360 internal id as external id with key `"sw360"` to the export.

**Comment by adrian-evo** [comment]
Imported the following file as lics, containing a single license and a single todo, both with external ids. The external ids are displayed fine in database, including for todo, but the todo cannot be seen on the UI.

[LicensesBackup4.zip](https://github.com/sw360/sw360portal/files/1449886/LicensesBackup4.zip)

**Pull request merged**
