### PR TITLE
feat(licenseinfo): clean license texts in license info generation

### PR DESCRIPTION
**Pull request by ChristophNiehoff**
tiny modification to the velocity template for plain text generation.
Removed xml-escaping.

### CODE REVIEW

**Comment by ChristophNiehoff** [comment]
@mcjaeger At least for my example files this results in nice looking license infos. Could you check if this small fix is sufficient?

**Comment by adrian-evo** [comment]
Tried with the attached file and I still can see some instances of &gt; in the generated txt file.

[CLI_Apache_Thrift-0.9.3.xml.zip](https://github.com/sw360/sw360portal/files/1394770/CLI_Apache_Thrift-0.9.3.xml.zip)

**Comment by alexbrdn** [comment]
I believe this fix is insufficient. It covers only the second bullet point from #559.

**Comment by ChristophNiehoff** [comment]
@alexbrdn In a private discussion we decided, that we concentrate on unescaping the HTML-escaped characters for the time being. And right now, we do not include rendering the HTML tags.

**Comment by alexbrdn** [comment]
Well, if it was private, how am I supposed to know?

Anyways... in light of what I just learned, I think the "Closes" tag in the PR description is incorrect. We don't want to auto-close the issue when this PR is merged, as it fixes only a part of the issue.

Apart from that, I can confirm that it works.

@adrian-evo, I think you made a mistaken assumption as to what is required of this fix. This PR shouldn't remove all instances of angle brackets from text (there are some in the original). What it should do is to generate text file without escaping the angle brackets and such as if it was generating an xml file.

**Comment by ChristophNiehoff** [comment]
@alexbrdn  Ok, yes. I agree. Removed the "Closes" tag.

**Comment by maxhbr** [comment]
The closes tag is still in the commit message:

**Comment by ChristophNiehoff** [comment]
@maxhbr You are faster in commenting than me in committing... ;)

Anyways, during rebase I realized that most part of this fix was already included in the already merged PR  https://github.com/sw360/sw360portal/pull/586 (authored by me). This makes the current PR kind of dispensable. However, the question is still open, whether this is sufficient.

**Comment by alexbrdn** [comment]
I believe it is sufficient to remove the xml escaping when generating text document - just as you have done.

**Pull request merged**
