### PR TITLE
Acknowledgements from CLI in License Info

### PR DESCRIPTION
**Pull request by alex-evo**
- added reading acknowledgements from CLI files for license info generation
- also added reading license names from CLI files (for xhtml output)

### CODE REVIEW

**Comment by alex-evo** [comment]
I was reviewing this PR and realized that it's incomplete. The acknowledgements are read from CLI files, but never output to the license info file. I believe it's because we never specified how they should look like in the output. @mcjaeger, need your input.

**Comment by mcjaeger** [comment]
@alex-evo if an acknowledgement exists for a component:

1. list these as acknowledgement in a section parallel to "copyrights" or "licenses"
2. list the component name + release version
3. list the acknowledgement

For elements without acknowledgement just ommit also mentioning the name

For text output the the following example (completely bogus data):

036 oss sw360 20161209 screenshot acknowledgement example 02

For XHTML as following:

036 oss sw360 20161209 screenshot acknowledgement example 03

For word, please add a column as following:

036 oss sw360 20161209 screenshot acknowledgement example 04

**Comment by mcjaeger** [comment]
Another example for the XHTML example:

036 oss sw360 20161209 screenshot acknowledgement example 05

**Comment by mcjaeger** [comment]
tested-by:michael.c.jaeger@siemens.com

**Comment by alex-evo** [comment]
Branch rebased. The PR is ready to merge now.

**Pull request merged**
