### PR TITLE
move bdpimport-backend to external package: remove it from sw360

### PR DESCRIPTION
**Pull request by bs-jokri**
Removes the bdp functionality from the backend that is already be moved to a separate repository.

### CODE REVIEW

**Comment by heydenreich** [comment]
rebased - ready to test and merge

**Comment by mcjaeger** [comment]
at import page, I noticed that there is still "BDP" in the pop up menu. It does not bother me much, but in case you intended to eliminate this I wanted to mention that.

**Comment by maximilianhuber** [comment]
At the moment, a new backup service (i.e. bdp) has no option to tell the project import portlet in the frontend that it is there, i.e. register itself. This list thus consists of the only valid option, which is currently available.

Once additional import services emerge, we have to think about an registration mechanism.

**Comment by mcjaeger** [comment]
I did also functional testing and just found the issue with the "BDP". Let's merge it, but who "all of you" is review-by: ?

**Comment by alex-evo** [comment]
There isn't much to review, frankly - a bunch of files deleted. I reviewed it. The right side looks much cleaner.

**Pull request merged**
